### ISSUE TITLE
Review Dijkstra's Algorithm

### ISSUE THREAD

**Issue by swangcs** [swangcs/spf_perf#1]
Including:
- the problem that DA can solve 
- basic flow
- time/space complexity
- possible applications

The output should be in the first weekly report https://github.com/swangcs/spf_perf/wiki/weeklyreport1.

**Comment by swangcs** [comment]
If you find it difficult to review DA, you can try to start with:
- depth-first search (DFS)
- breadth-first search (BFS)
@GabLah

**Comment by GabLah** [comment]
## The problem that DA can solve

Find the shortest path(all-pairs shortest paths)

## Basic Flow:

### Input: 

- Graph G = (V,E), m = | E |, n = | V |

- ##### Each edge has non-negative length.

- An originating vertex — source vertex s

### Output:

For each v belongs to V, compute L(v) = length of a shortest s-v pathing.

### Assumption:

The length to source vertex is plus infinity before marked.

### Pseudocode:

#### Initialize:

X = {s}, vertices has been computed shortest path distance

In each iteration, conquer one new vertex after m minus 1 iteration.

A[s], the output. For each vertex, have an entry in the array A.

##### Main loop:

while X != w:  grow X by one node

among all edges (v,w) belongs to E with v belongs to X, w does not belong to X

pick the one that minimizes A[v] + L (v-w)

When v has multiple w (cross the frontier edges from v), the most suitable vertex is w*.

v*, w* guide to the vertex should add the x next.

Add w* to x that is one more vertex in x.

Set A[w*] = A[v*] +Lv*w*

#### Speeding-up using heap:

The smallest key of them all has to be at the root of this tree.

Finding minimums in logarithmic time.

##### Invarients:

1.	vertices of v-w

2.	key[w] = smallest score

The final proposed vertex that comes out of the heap. This key update will be logarithmic time.

When v extracts from heap: (i.e. added to X)

for each edge (v,w) belongs to E:

if w belongs to V-X (i.e. in heap)

–	delete w from heap

–	recompute key[w] = min{key[w], A[v]+L(v,w)}

–	re_insert v into heap

 

## **Time/space complexity:** 

Time: O(mn), Heap — O(m * log n)

Space:  O(n) — heap, O(n^2) — Adjacency matrix

## **Possible applications:**

Geographical Maps

–	Find locations of Map which refers to vertices of a graph

–	Distance between the location refers to edges

IP routing

Biology

–	find the cellular network model in spreading of an infectious disease

**Comment by GabLah** [comment]
I still have trouble finding the correct space complexity. Please help me out. @swangcs

**Comment by swangcs** [comment]
> I still have trouble finding the correct space complexity. Please help me out. @swangcs

About the space complexity, @GabLah see screenshot below from Wikipedia:
![image](https://user-images.githubusercontent.com/4038577/58408632-c1705d00-80a0-11e9-9359-e399f8e7e784.png)

**Comment by swangcs** [comment]
> ## The problem that DA can solve
> For a given source node in the graph, the algorithm finds the shortest path between that node and every other.
> 
> It can also be used for finding the shortest paths from a single node to a single destination node by stopping the algorithm once the shortest path to the destination node has been determined.
> 
> ## Basic Flow:
> ### Input:
> * Graph G = (V,E), m = | E |, n = | V |
> * Each edge has non-negative length.
> * An originating vertex — source vertex s
> 
> ### Output:
> For each v belongs to X, compute L(v) = length of a shortest s-v pathing.
> 
> For each v belongs to X, record P(v) = the shortest path from s to v.
> 
> ### Pseudocode:
> #### Initialize:
> X = {s}, vertices has been computed shortest path distance
> 
> In each iteration, conquer one new vertex after m minus 1 iteration.
> 
> A[s], the output, the length of the path to source vertex is positive infinity before marked. For each vertex, have an entry in the array A.
> 
> B[s], the output, each path starts from s. For each vertex, have an entry in the array B.
> 
> ##### Main loop:
> While w not in X: grow X by one node w
> 
> Among all edges (v,w) belongs to E with v belongs to X, w does not belong to X
> 
> Pick the one that minimizes A[v] + L (v-w)
> 
> #### Finish:
> A[s] and B[s] store the shortest path and the length of the path for every vertex respectively.
> 
> #### Speeding-up using heap:
> Binary search tree to optimize the time to pick one vertex that minimizes A[v] + L (v-w)
> 
> The smallest key of them all has to be at the root of this tree.
> 
> Finding minimums in logarithmic time.
> 
> ##### Invarients:
> 1. vertices of v-w
> 2. key[w] = smallest score
> 
> When v extracts from heap: (i.e. added to X)
> 
> for each edge (v,w) belongs to E:
> 
> if w belongs to V-X (i.e. in heap)
> 
> –	delete w from heap
> 
> –	recompute key[w] = min{key[w], A[v]+L(v,w)}
> 
> –	re_insert v into heap
> 
> ## **Time/space complexity:**
> Time: O(mn), Heap — O(m * log n)
> 
> Space:
> 
> O(n) — heap, O(n^2) — Adjacency matrix for a graph
> 
> ## **Possible applications:**
> Geographical Maps
> 
> –	Find locations of Map which refers to vertices of a graph
> 
> –	Distance between the location refers to edges
> 
> IP routing
> 
> Social network
> 
> Biology
> 
> –	Find the cellular network model in spreading of an infectious disease
> 
> [https://www.coursera.org/learn/algorithms-graphs-data-structures](url) lessons in week 4
> [https://blog.csdn.net/yangcs2009/article/details/40109511](url)
> [https://blog.csdn.net/stanfordzhang/article/details/6626584](url)

@GabLah This is a great first try! Maybe summarize and reorganize them in LaTex #5
