### ISSUE TITLE
Baseline Dijkstra's Algorithm in Java

### ISSUE THREAD

**Issue by swangcs** [swangcs/spf_perf#2]
This is to implement the original version of DA, where you use the O(N) algorithm to extend the node with the minimum cost for each iteration.

**Comment by GabLah** [comment]
In the process of implementing the algorithm, I have raised a lot of questions that I hadn't thought of before, so there are some differences between the way the code implements the DA algorithm and the Latex file description before, so I need to change the file to match the code, right? Or change the code?

**Comment by GabLah** [comment]
The graph used to test the DA algorithm comes from this video: [https://v.youku.com/v_show/id_XMjQyOTY1NDQw.html](Dijkstra algorithm)

**Comment by swangcs** [comment]
I have uploaded my implementation. c2ee9638b64e906600406715b33ff32b6147e07b
Please compare and commit your improved one @GabLah .
