### ISSUE TITLE
Writing in LaTex

### ISSUE THREAD

**Issue by swangcs** [swangcs/spf_perf#5]
Writing down your literature survey progressively, using your own words, in LaTex:
- suggested tool: [overleaf](https://www.overleaf.com/)
- reasons:
  - professional research paper all written in LaTex
  - better representations of mathematical notations than using Markdown
- summarize your understanding on DA first. Then, commit your LaTex source file, with figures if necessary, to our repository: https://github.com/swangcs/spf_perf/tree/master/paper

**Comment by GabLah** [comment]
[https://www.youtube.com/user/ShareLaTeX/videos](url) LaTex Tutorial pt1 - 7
[https://blog.csdn.net/Gentleman_Qin/article/details/79963396](url)

**Comment by swangcs** [comment]
> [https://www.youtube.com/user/ShareLaTeX/videos](url) LaTex Tutorial pt1 - 7
> [https://blog.csdn.net/Gentleman_Qin/article/details/79963396](url)

Looks good to me!

**Comment by GabLah** [comment]
[https://www.cnblogs.com/Coolxxx/p/5982439.html](url) Mathematical notations
