### ISSUE TITLE
Correct use of references in LaTeX

### ISSUE THREAD

**Issue by swangcs** [swangcs/spf_perf#6]
Learn and practice how to use references in  LaTeX, in particular:

- how to search the original academic paper for some important algorithms in your paper, e.g. DA
- how to use ``bibtex`` to describe paper references and integrate them with your existing LaTeX paper

**Comment by GabLah** [comment]
[https://tex.stackovernet.com/cn/q/65988](url) Why are URLs not appearing in References with Bibtex?
[https://www.overleaf.com/learn/latex/Errors/Underfull_%5Chbox](url) Underfull error
[http://xiaosheng.me/2017/02/03/article28/](url) learn how to edit mathematical formulas

Errors will be reported by using the following web pages:
[https://blog.csdn.net/robert_chen1988/article/details/73555471](url)
[https://blog.csdn.net/jianwushuang/article/details/53572972](url)

**Comment by swangcs** [comment]
> [https://tex.stackovernet.com/cn/q/65988](url) Why are URLs not appearing in References with Bibtex?
> [https://www.overleaf.com/learn/latex/Errors/Underfull_%5Chbox](url) Underfull error
> [http://xiaosheng.me/2017/02/03/article28/](url) learn how to edit mathematical formulas
> 
> Errors will be reported by using the following web pages:
> [https://blog.csdn.net/robert_chen1988/article/details/73555471](url)
> [https://blog.csdn.net/jianwushuang/article/details/53572972](url)

Hey, these links are not even shown correctly in markdown here, plz debug this first.
