### ISSUE TITLE
A basic testing framework

### ISSUE THREAD

**Issue by swangcs** [swangcs/spf_perf#9]
Write a basic testing framework that can:
- load different datasets
- for a dataset, testing different SPF implementations
- results summarized in ``dataset name, SPF algorithm name, running time (average by 5 runs)``

**Comment by swangcs** [comment]
Here is an example to list the algorithms that you are going to test:
- DA with O(n) min (list & matrix)
- DA with HEAP (list & matrix)
- A* with (list & matrix)

In total, you should have 6 algorithms  to test on **road network datasets**

Now please prepare "datasets" and evaluation "metrics" to finish your testing @GabLah 

Note, that very small sample graph data you have is only for testing the correctness (not performance) of your implementation, which should not be included here.

**Comment by GabLah** [comment]
All modified code has been uploaded.
The only problem is that when the data set is too large, the maximum connected component obtained through DFS is not completely correct, and there are still disconnected data. 
It seems like this problem only occurs when using map data in the Dublin_l.osm. @swangcs
